# Generated by Django 6.0.3 on 2026-03-19 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/', verbose_name='Картинка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('users', models.ManyToManyField(blank=True, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
    ]
