# Generated by Django 6.0.3 on 2026-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='exams', to='auth.group', verbose_name='Группы'),
        ),
    ]
